# ============================================================================
# Terraform Backend Configuration - Cross-region Infrastructure
# ============================================================================
# Scope: cross-region
# Environment: production
# Region: us-east-2
# Auto-generated by manage-tenant-backends.sh
# ============================================================================

bucket         = "us-east-2-prod-terraform-state-production"
key            = "global/cross-region/terraform.tfstate"
region         = "us-east-2"
dynamodb_table = "terraform-locks-us-east"
encrypt        = true

# State locking configuration
dynamodb_table_tags = {
  Project     = "us-east-2-prod"
  Environment = "production"
  Region      = "us-east-2"
  Scope       = "cross-region"
  ManagedBy   = "Terraform"
}

# S3 bucket configuration validation
s3_bucket_tags = {
  Project     = "us-east-2-prod"
  Environment = "production"
  Region      = "us-east-2"
  Purpose     = "terraform-backend"
  Scope       = "cross-region"
}
