# ============================================================================
# S3 Infrastructure Provisioning - Auto-generated
# ============================================================================
# This file is auto-generated by provision-s3-infrastructure.sh
# Region: us-east-2
# Environment: production
# Project: ohio-01
# ============================================================================

terraform {
  required_version = ">= 1.5.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = "us-east-2"
  
  default_tags {
    tags = {
      Project            = "ohio-01"
      Environment        = "production"
      Region             = "us-east-2"
      ManagedBy          = "Terraform"
      ProvisionedBy      = "s3-provisioning-script"
      Company            = "Zam Ltd"
      Architecture       = "Multi-Client"
    }
  }
}

# Backend State Infrastructure
module "terraform_backend_state" {
  source = "../../modules/terraform-backend-state"
  
  # Core configuration
  project_name       = "ohio-01"
  environment        = "production"
  region            = "us-east-2"
  region_short_name = "us-east"
  
  # Custom naming
  custom_bucket_name   = "ohio-01-terraform-state-production"
  custom_dynamodb_name = "terraform-locks-us-east"
  
  # Security - Enhanced for critical infrastructure
  kms_key_id     = ""
  prevent_destroy = true
  
  # Enterprise Security Features
  enable_versioning = true
  enable_mfa_delete = false   # Set to true in production with MFA device
  object_ownership = "BucketOwnerEnforced"
  
  # Access Logging - Critical for state file access tracking
  enable_access_logging = true
  
  # Advanced Monitoring - Essential for state management
  enable_cloudwatch_metrics = true
  enable_eventbridge = true
  
  # Cross-region replication
  enable_cross_region_replication = false
  replication_destination_bucket_arn = "" != "" ? "arn:aws:s3:::ohio-01-terraform-state-production-replica" : ""
  
  # Backend configuration generation
  generate_backend_configs = true
  backend_config_output_path = "../../backends/aws"
  
  # Monitoring
  enable_backend_monitoring = true
  enable_state_monitoring  = true
  
  # Common tags
  common_tags = {
    CreatedBy = "provision-s3-infrastructure.sh"
    Purpose   = "Terraform-Backend-Infrastructure"
    SecurityLevel = "Critical"
    MonitoringEnabled = "true"
    DataClassification = "Infrastructure"
  }
}

# Observability Buckets
module "logs_bucket" {
  source = "../../modules/s3-bucket-management"
  
  project_name   = "ohio-01"
  environment    = "production"
  region        = "us-east-2"
  bucket_purpose = "logs"
  
  # Lifecycle optimized for logs with structured keys
  logs_retention_days = 90
  enable_intelligent_tiering = true
  enable_structured_keys = true
  
  # Enterprise Security Features
  enable_versioning = true
  enable_mfa_delete = false  # Enable in production with MFA device
  versioning_mfa_delete = false
  object_ownership = "BucketOwnerEnforced"
  
  # Access Logging
  enable_access_logging = true
  access_logs_prefix = "access-logs/logs-bucket/"
  
  # Performance Optimization
  enable_transfer_acceleration = false  # Enable for global access
  enable_request_payer = false
  
  # Advanced Monitoring
  enable_cloudwatch_metrics = true
  enable_analytics_configuration = true
  enable_inventory_configuration = true
  
  # Notifications
  enable_bucket_notifications = true
  enable_eventbridge = true
  
  # Custom key patterns for better organization
  custom_key_patterns = {
    logs = {
      enabled = true
      pattern = "logs/cluster=$${cluster_name}/tenant=$${tenant}/service=$${service}/year=%Y/month=%m/day=%d/hour=%H/fluent-bit-logs-%Y%m%d-%H%M%S-$$UUID.gz"
      partitions = ["cluster_name", "tenant", "service", "year", "month", "day", "hour"]
    }
  }
  
  # Security
  kms_key_id = ""
  
  # Cross-region replication
  enable_cross_region_replication = false
  replication_destination_bucket_arn = "" != "" ? "arn:aws:s3:::ohio-01-us-east-2-logs-production-replica" : ""
  
  common_tags = {
    CreatedBy = "provision-s3-infrastructure.sh"
    Purpose   = "Application-Logs-Storage"
    SecurityLevel = "High"
    MonitoringEnabled = "true"
  }
}

module "traces_bucket" {
  source = "../../modules/s3-bucket-management"
  
  project_name   = "ohio-01"
  environment    = "production"
  region        = "us-east-2"
  bucket_purpose = "traces"
  
  # Lifecycle optimized for traces with structured keys
  traces_retention_days = 30
  enable_intelligent_tiering = true
  enable_structured_keys = true
  
  # Enterprise Security Features
  enable_versioning = true
  enable_mfa_delete = false
  versioning_mfa_delete = false
  object_ownership = "BucketOwnerEnforced"
  
  # Access Logging
  enable_access_logging = true
  access_logs_prefix = "access-logs/traces-bucket/"
  
  # Performance Optimization
  enable_transfer_acceleration = false
  enable_request_payer = false
  
  # Advanced Monitoring
  enable_cloudwatch_metrics = true
  enable_analytics_configuration = true
  enable_inventory_configuration = true
  
  # Notifications
  enable_bucket_notifications = true
  enable_eventbridge = true
  
  # Custom key patterns for better organization
  custom_key_patterns = {
    traces = {
      enabled = true
      pattern = "traces/cluster=$${cluster_name}/tenant=$${tenant}/service=$${service}/year=%Y/month=%m/day=%d/hour=%H/tempo-traces-%Y%m%d-%H%M%S-$$UUID.gz"
      partitions = ["cluster_name", "tenant", "service", "year", "month", "day", "hour"]
    }
  }
  
  # Security
  kms_key_id = ""
  
  # Cross-region replication
  enable_cross_region_replication = false
  replication_destination_bucket_arn = "" != "" ? "arn:aws:s3:::ohio-01-us-east-2-traces-production-replica" : ""
  
  common_tags = {
    CreatedBy = "provision-s3-infrastructure.sh"
    Purpose   = "Distributed-Traces-Storage"
    SecurityLevel = "High"
    MonitoringEnabled = "true"
  }
}

module "metrics_bucket" {
  source = "../../modules/s3-bucket-management"
  
  project_name   = "ohio-01"
  environment    = "production"
  region        = "us-east-2"
  bucket_purpose = "metrics"
  
  # Lifecycle optimized for metrics with structured keys
  metrics_retention_days = 90
  enable_intelligent_tiering = true
  enable_structured_keys = true
  
  # Enterprise Security Features
  enable_versioning = true
  enable_mfa_delete = false
  versioning_mfa_delete = false
  object_ownership = "BucketOwnerEnforced"
  
  # Access Logging
  enable_access_logging = true
  access_logs_prefix = "access-logs/metrics-bucket/"
  
  # Performance Optimization
  enable_transfer_acceleration = false
  enable_request_payer = false
  
  # Advanced Monitoring
  enable_cloudwatch_metrics = true
  enable_analytics_configuration = true
  enable_inventory_configuration = true
  
  # Notifications
  enable_bucket_notifications = true
  enable_eventbridge = true
  
  # Custom key patterns for better organization
  custom_key_patterns = {
    metrics = {
      enabled = true
      pattern = "metrics/cluster=$${cluster_name}/metric_type=$${metric_type}/year=%Y/month=%m/day=%d/hour=%H/prometheus-metrics-%Y%m%d-%H%M%S-$$UUID.json.gz"
      partitions = ["cluster_name", "metric_type", "year", "month", "day", "hour"]
    }
  }
  
  # Security
  kms_key_id = ""
  
  # Cross-region replication
  enable_cross_region_replication = false
  replication_destination_bucket_arn = "" != "" ? "arn:aws:s3:::ohio-01-us-east-2-metrics-production-replica" : ""
  
  common_tags = {
    CreatedBy = "provision-s3-infrastructure.sh"
    Purpose   = "Prometheus-Metrics-Storage"
    SecurityLevel = "High"
    MonitoringEnabled = "true"
  }
}

module "audit_logs_bucket" {
  source = "../../modules/s3-bucket-management"
  
  project_name   = "ohio-01"
  environment    = "production"
  region        = "us-east-2"
  bucket_purpose = "audit_logs"
  
  # Lifecycle optimized for audit logs with long retention
  audit_logs_retention_days = 2555  # 7 years for compliance
  enable_intelligent_tiering = true
  enable_structured_keys = true
  
  # Enterprise Security Features - Enhanced for compliance
  enable_versioning = true
  enable_mfa_delete = false   # Set to true for production compliance
  versioning_mfa_delete = false
  object_ownership = "BucketOwnerEnforced"
  
  # Access Logging - Required for audit trails
  enable_access_logging = true
  access_logs_prefix = "access-logs/audit-logs-bucket/"
  
  # Performance Optimization
  enable_transfer_acceleration = false
  enable_request_payer = false
  
  # Advanced Monitoring - Critical for compliance
  enable_cloudwatch_metrics = true
  enable_analytics_configuration = true
  enable_inventory_configuration = true
  
  # Notifications - Required for security monitoring
  enable_bucket_notifications = true
  enable_eventbridge = true
  
  # Custom key patterns for better organization
  custom_key_patterns = {
    audit_logs = {
      enabled = true
      pattern = "audit-logs/cluster=$${cluster_name}/component=$${component}/year=%Y/month=%m/day=%d/hour=%H/k8s-audit-%Y%m%d-%H%M%S-$$UUID.json.gz"
      partitions = ["cluster_name", "component", "year", "month", "day", "hour"]
    }
  }
  
  # Security - Enhanced for compliance
  kms_key_id = ""  # Consider using KMS for audit logs in production
  
  # Cross-region replication - Recommended for audit logs
  enable_cross_region_replication = false
  replication_destination_bucket_arn = "" != "" ? "arn:aws:s3:::ohio-01-us-east-2-audit-logs-production-replica" : ""
  
  common_tags = {
    CreatedBy = "provision-s3-infrastructure.sh"
    Purpose   = "Kubernetes-Audit-Logs-Storage"
    Compliance = "SOC2-PCI-GDPR"
    SecurityLevel = "Critical"
    MonitoringEnabled = "true"
    DataClassification = "Sensitive"
  }
}
