apiVersion: apps/v1
kind: Deployment
metadata:
  name: trace-generator
  namespace: istio-system
  labels:
    app: trace-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trace-generator
  template:
    metadata:
      labels:
        app: trace-generator
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: trace-generator
        image: curlimages/curl:latest
        command: 
        - /bin/sh
        - -c
        - |
          while true; do
            echo "Generating trace..."
            curl -H "x-request-id: $(date +%s)-$(uuidgen)" -s -o /dev/null http://httpbin.org/delay/1 || true
            sleep 10
          done
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
          limits:
            cpu: 50m
            memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: trace-generator
  namespace: istio-system
spec:
  selector:
    app: trace-generator
  ports:
  - port: 80
    targetPort: 8080
